spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  application:
    name: spring-jba
  datasource:
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5432/spring-jba
    driver-class-name: org.postgresql.Driver
  # jpa and data source config
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /
file_storage:
  image_location: "filestorage/images/"
  client_path: "/images/**"
  data_location: "filestorage/data"